Card Transaction Request
cuenca-mx/cuenca-validations pull request #130
Opened 2021-04-30 16:41 UTC by chiqeen03

elimina código duplicado desde core, accendo-authorizer, y card-authorizer

Closes #129

2021-04-30 18:10 UTC, alexviquez requested changes
types hacen referencia a valores definidos, como los enum, para el caso de merchant creo que puedes tener un objeto anidado y sería más descriptivo

2021-04-30 18:10 UTC, alexviquez commented on cuenca_validations/types/requests.py
> +    transaction_type: str
igual que arriba, podría ser un type

2021-04-30 18:10 UTC, alexviquez commented on cuenca_validations/types/requests.py
> +    pos_capability: Optional[str]
debería ser enum

2021-04-30 19:25 UTC, alexviquez requested changes
Hay campos de la herencia que se repiten, unificar y reusar CardTransactionRequest

2021-04-30 19:46 UTC, chiqeen03 commented on cuenca_validations/types/requests.py
> +    transaction_type: str
Actualmente en el autorizador se está manejando como enum, pero acá y en core se maneja como str. Consideramos que incluirlo acá significaría un cambio mayo en Core que implica migraciones a la base de datos.

2021-04-30 19:54 UTC, chiqeen03 commented on cuenca_validations/types/requests.py
> +    merchant_data: str
Creo que por la forma en la que está construido el modelo [Transaction](https://github.com/cuenca-mx/card-authorizer/blob/arqc_validation/authorizer/models/transactions.py#L82-L84) en el authorizer, implicaría hacer un cambio estructural en el modelo de mongo, y crear una migración. La forma de llenar los modelos es solamente con un [to_dic()](https://github.com/cuenca-mx/card-authorizer/blob/arqc_validation/authorizer/models/transactions.py#L201-L210)

2021-04-30 20:05 UTC, chiqeen03 commented on cuenca_validations/types/requests.py
> +    transaction_type: str
mismo de arriba

2021-04-30 20:05 UTC, chiqeen03 commented on cuenca_validations/types/requests.py
> +    pos_capability: Optional[str]
mismo de arriba

2021-05-06 18:38 UTC, alexviquez requested changes
quedo mejor con los enums y la herencia bien aplicada, solo dos comments

2021-05-06 18:38 UTC, alexviquez commented on cuenca_validations/types/__init__.py
> +    'UserCardNotification',
Acomodar en orden alfabetico

2021-05-06 18:38 UTC, alexviquez commented on cuenca_validations/types/requests.py
> +    authorizer_number: Optional[str]
authorizer number no debería tener un validador? es decir siempre son digitos, a pesar de ser un string podríamos aplicarle una regex para garantizar que no tengan letras o así

2021-05-06 18:41 UTC, pachCode commented on cuenca_validations/types/requests.py
> +    authorizer_number: Optional[str]
En locales sí pero para internacionales según la documentación te permite alfanumericos, no lo hacemos así porque prosa no soporta pero posiblemente con Masteercard se pueda

2021-05-06 18:43 UTC, alexviquez commented
faltan test de los request

2021-05-06 18:43 UTC, alexviquez commented on cuenca_validations/types/requests.py
> +    authorizer_number: Optional[str]
ha entonces mejor lo dejamos abierto

2021-05-06 18:45 UTC, alexviquez commented
debes renombrar `NotificationRequest ` el dataclass solo hace referencia a un CardNotification, dejar NotificationRequest podría pensarse que el uso es de otro sistema ajeno a las tarjetas

2021-05-13 21:55 UTC, alexviquez approved these changes
creo que esta bien.

2021-05-17 21:51 UTC, merged