Wallets types and request
cuenca-mx/cuenca-validations pull request #153
Opened 2021-07-19 17:24 UTC by pachCode

Add wallet type into TransferNetwork
Add Currency enum
Add WalletType enum
Add SavingRequest model

2021-07-20 20:10 UTC, matin commented on cuenca_validations/types/requests.py
> +from datetime import datetime
`import datetime as dt`

2021-08-13 22:42 UTC, matin reviewed
me parece bien. ¿pueden actualizar la versión y quitar el estatus de draft?

2021-09-03 18:54 UTC, alexviquez requested changes
unos comments

2021-09-03 18:54 UTC, alexviquez commented on cuenca_validations/types/requests.py
> +    category: SavingCategory
deberías agregar opcionales los otros dos campos (goal_date, goal_amount), en app no lo hacemos así pero la librería debería soportarlo no ?

2021-09-03 18:54 UTC, alexviquez commented on cuenca_validations/version.py
> +__version__ = '0.9.11.dev7'
cambiar versión

2021-09-03 18:54 UTC, alexviquez commented on tests/test_types.py
> +    SavingUpdateRequest(**data)
Separa el update y el request en test diferentes

2021-09-03 19:00 UTC, rogelioLpz commented on cuenca_validations/types/requests.py
> +    category: SavingCategory
`SavingUpdateRequest` ya tiene esos campos opcionales, por eso ya no se vuelven a definir

2021-09-03 19:04 UTC, alexviquez commented on cuenca_validations/types/requests.py
> +    category: SavingCategory
Es rara como se ocupa la herencia

2021-09-03 19:20 UTC, alexviquez approved these changes
Por mi esta bien

2021-09-07 23:37 UTC, merged