Types and requests for identify
cuenca-mx/cuenca-validations pull request #179
Opened 2021-11-09 18:57 UTC by chiqeen03

2021-11-16 20:38 UTC, pachCode commented on cuenca_validations/types/enums.py
> +    govt_id = 'govt_id'
Este puede ser de varios tipos https://github.com/cuenca-mx/core/blob/59b7985ec479e531456d0377cc8bbe19ad8b7707/core/types.py#L19

2021-11-16 20:41 UTC, pachCode commented on cuenca_validations/types/identities.py
> +    estado: str
Estado puede ser un enum

2021-11-16 20:41 UTC, pachCode commented on cuenca_validations/types/identities.py
> +    phone_number: str
debe ser un tipo phone_number

2021-11-16 20:43 UTC, pachCode commented on cuenca_validations/types/identities.py
> +    feedme_uri: Optional[str]
feedme_uri y value por qué están?

2021-11-16 20:44 UTC, pachCode commented on cuenca_validations/types/identities.py
> +    data: Optional[str]
Este podría ser un dict, así si quisieramos hacer ocr podríamos poner los datos obtenidos en el documento

2021-11-16 21:38 UTC, chiqeen03 commented on cuenca_validations/types/identities.py
> +    feedme_uri: Optional[str]
se me fue de cuando era UserProof jaja

2021-11-17 17:01 UTC, felipaoo requested changes

2021-11-17 17:01 UTC, felipaoo commented on cuenca_validations/types/requests.py
> +    birth_country: Optional[str] = None
porqué son opcionales?

2021-11-18 19:07 UTC, matin commented on cuenca_validations/types/enums.py
> +    residence = 'residence'
`residency`

2021-11-18 19:13 UTC, matin commented on cuenca_validations/types/identities.py
> +class PhoneNumber(str):
inherit from `ConstrainedStr`

2021-11-18 19:33 UTC, matin commented on cuenca_validations/types/requests.py
> +    email_address: str
`EmailStr`

2022-01-07 00:15 UTC, rogelioLpz commented on cuenca_validations/types/enums.py
> +class States(Enum):
`EntidadFederativa`

https://gist.github.com/matin/321a2631f7a029ffb564c4c7980390e1

2022-01-18 16:21 UTC, pachCode commented on cuenca_validations/types/__init__.py
> +    'UserCreationRequest',
Sería solo UserRequest no?

2022-01-18 16:23 UTC, pachCode commented on cuenca_validations/types/enums.py
> +    validation_succeeded = 'validation_succeeded'
Por qué se necesita validation_succeeded y validation_failed? Si no es por algo en especial solo

2022-01-18 16:24 UTC, pachCode commented on cuenca_validations/types/enums.py
> +    validation_succeeded = 'validation_succeeded'
quizás solo succeeded y failed estaría bien

2022-01-18 19:02 UTC, alexviquez requested changes
puse unos comments más respecto a los query's

2022-01-18 19:02 UTC, alexviquez commented on cuenca_validations/types/queries.py
> +    blacklist_validation_status: Optional[VerificationStatus] = None
para los query en realidad solo ponemos los que tiene sentido ocupar, por ejemplo:
```python
rfc
curp
status
```
revisar los demás, no tiene sentido filtrar por nombre no veo un caso en el que lo hicieramos

2022-01-18 19:02 UTC, alexviquez commented on cuenca_validations/types/queries.py
> +    blacklist_validation_status: Optional[VerificationStatus] = None
los demás me refiero a EventQuery y UserQuery

2022-01-18 19:02 UTC, alexviquez commented on cuenca_validations/types/requests.py
> +class UserCreationRequest(BaseModel):
UserRequest

2022-01-18 19:11 UTC, alexviquez commented on cuenca_validations/types/identities.py
> +    feedme_uri_back: Optional[str] = None
o front_uri jeje

2022-01-26 22:09 UTC, felipaoo requested changes
íralo

algunos detalles. 

Solo tengo duda en el  validator `PhoneNumber`, no estoy seguro si 13 sea adecuado para `max_length` veo que hay número de otros países que tienen más dígitos

2022-01-26 23:28 UTC, chiqeen03 commented on cuenca_validations/types/requests.py
> +    @validator('beneficiary')
no hay límite, mientras sumen 100

2022-01-27 19:32 UTC, felipaoo approved these changes
Se ve bien! a menos que hayan otras observaciones por parte de @pachCode o @rogelioLpz

2022-01-28 20:15 UTC, alexviquez requested changes
cambios pequeños

2022-01-28 20:15 UTC, alexviquez commented on cuenca_validations/types/requests.py
> +    manual_curp: Optional[CurpField] = None
no sería mejor ponerle solo curp? sabemos que es manual cuando ingresa por medio del request no ?

2022-01-28 20:15 UTC, alexviquez commented on tests/test_types.py
> +    UserRequest(**request)
mete asserts para validar que se hizo bien el mapeo del objeto

2022-01-28 20:15 UTC, alexviquez commented on tests/test_types.py
> +    CurpValidationRequest(**request)
asserts

2022-01-28 20:15 UTC, alexviquez commented on tests/test_types.py
> +    UserUpdateRequest(**request)
asserts

2022-01-28 23:34 UTC, rogelioLpz commented on cuenca_validations/types/identities.py
> +    version: int
Sería un str no @alexviquez ?
`version:"2022-01-28"`

2022-01-28 23:35 UTC, rogelioLpz commented on cuenca_validations/types/identities.py
> +    type: str  # hay que definir bien
Ese comment de `hay que definir bien` continua vigente ?
O ya se aclaro ?

2022-01-28 23:47 UTC, rogelioLpz commented on cuenca_validations/types/requests.py
> +    names: str
`name` o `names` @matin ?
https://gist.github.com/matin/989bbe9fbe4a2af92d1e5c0d33867745

2022-01-28 23:47 UTC, alexviquez commented on cuenca_validations/types/identities.py
> +    version: int
si, un string es suficiente

2022-01-31 21:50 UTC, rogelioLpz commented on cuenca_validations/types/requests.py
> +    state_of_birth: Optional[State] = None
Ninguno de estos atributos se deben modificar. 
Si el `Identity` se genera a partir de la Info de Renapo. No hay razón para actualizarla

2022-02-01 00:04 UTC, rogelioLpz commented on cuenca_validations/types/enums.py
> +    created = 'created'
Que le falta a este cambio @alexviquez ?

2022-02-01 02:36 UTC, rogelioLpz commented on cuenca_validations/types/requests.py
> +    manual_curp: Optional[CurpField] = None
Es `manual_curp` para ser consistente con la respuesta. 
El modelo de [curp_validation](https://github.com/cuenca-mx/identify/blob/curp-validations/identify/models/curp_validations.py#L23) tiene otros campos de curp y es más claro si se mantiene así

2022-02-01 16:29 UTC, alexviquez requested changes
solo 3 comments y ya fierro

2022-02-01 16:29 UTC, alexviquez commented on cuenca_validations/version.py
> +__version__ = '0.9.17.dev30'
version

2022-02-01 16:29 UTC, alexviquez commented on tests/test_types.py
> +    CurpValidationRequest(**request)
este

2022-02-01 21:38 UTC, alexviquez submitted a review, later dismissed
pongan bien la versión y fuego

2022-02-01 21:42 UTC, felipaoo approved these changes

2022-02-01 21:44 UTC, merged