Identify models
cuenca-mx/cuenca-validations pull request #202
Opened 2022-02-09 15:14 UTC by pachCode

Add country  type and some mior changes

2022-02-09 17:16 UTC, chiqeen03 commented on cuenca_validations/types/requests.py
> -    @validator('curp')
voy a quitar este validador de User porque en curps con fechas ambiguas como 660606, toma 2066-06-06. Creo que con el validador que está en CurpValidationRequest es suficiente, pero sino pienso en una mejor opción

2022-02-10 19:20 UTC, alexviquez requested changes
Unos comments pequeñis

2022-02-10 19:20 UTC, alexviquez commented on cuenca_validations/types/requests.py
> +            and values['country_of_birth'] == 'MX'
El country_of_birth es un campo que siempre va a venir, si el problema es la validación que es pre, puedes quitarla para garantizar que siempre este y dejar el  if con solo dos sentencias

2022-02-10 19:20 UTC, alexviquez commented on cuenca_validations/types/requests.py
> +        birth_date = dt.datetime.strptime(century + curp_date, '%Y%m%d')
estew código es repetitivo, si necesitas usarlo aquí crea una función para esto:
```python
@validator('date_of_birth')
    def validate_birth_date(cls, date_of_birth: dt.date) -> dt.date:
        current_date = dt.datetime.utcnow()
        if relativedelta(current_date, date_of_birth).years < 18:
            raise ValueError('User does not meet age requirement.')
        return date_of_birth
```

si no es necesario por el curp validation, solo borralo (que estoy de acuerdo el curp validation es la fuente de la verdad xd)

2022-02-10 19:20 UTC, alexviquez commented on cuenca_validations/types/requests.py
> +    failure_url: Optional[AnyUrl] = None
puedes agregar un solo test de esto, para garantizar que metan una url

2022-02-11 20:56 UTC, alexviquez requested changes
unos comentarios pequeños

2022-02-11 20:56 UTC, alexviquez commented on cuenca_validations/validators.py
> +def check_age_requirement(birth_date: dt.date) -> dt.date:
para ser consistente con el nombre de los otros validadores usa:
`validate_age_required`

2022-02-11 20:56 UTC, alexviquez commented on cuenca_validations/types/requests.py
> +        check_age_requirement(birth_date)
la forma preferida para no tener que revisar que exception genera la función y lo más pythonic es cachar la exception y hacer un raise, voy a buscar el pep de esto porque no recuerdo como se llama, pero es algo que hacemos en core también sería algo así:
```python
try:
    validate_age_required(birth_date)
except ValueError:
    raise

```

2022-02-11 21:10 UTC, alexviquez approved these changes
dale!

2022-02-11 21:24 UTC, merged