`patzcuaro` types
cuenca-mx/cuenca-validations pull request #203
Opened 2022-02-09 20:04 UTC by LuisBrime

PR – WIP

2022-02-09 20:49 UTC, alexviquez requested changes

2022-02-09 20:49 UTC, alexviquez commented on cuenca_validations/types/queries.py
> +    extension: Optional[str] = None
remover este filtrado, creo que solo tiene sentido filtrar por type

2022-02-09 20:49 UTC, alexviquez commented on cuenca_validations/types/requests.py
> +    file: bytes
user_id no se si lo ocupes acá

2022-03-04 21:53 UTC, alexviquez requested changes
Creo que la lógica de calcular extensión y los bites debería vivir en el back

2022-03-04 21:53 UTC, alexviquez commented on cuenca_validations/types/files.py
> +    id: Optional[str]
porque el id es opcional?

2022-03-04 21:53 UTC, alexviquez commented on cuenca_validations/types/queries.py
> +    type: KYCFileType
debería ser opcional el type

2022-03-04 21:53 UTC, alexviquez commented on cuenca_validations/version.py
> +__version__ = '0.9.20.dev10'
cambiar version

2022-03-04 21:53 UTC, alexviquez commented on cuenca_validations/types/requests.py
> +        return guess_extension(mime) or 'none'
Esta lógica debería vivir en patzcuaro

2022-03-05 05:18 UTC, LuisBrime commented on cuenca_validations/types/files.py
> +    id: Optional[str]
porque este `Metadata` se usa para los archivos que se reciben para subir y los que se regresan en la descarga; los primeros no traen ID cuando lo mandan en `FileBatch`

2022-03-07 18:30 UTC, merged