Verifications 🛂
cuenca-mx/cuenca-validations pull request #213
Opened 2022-03-11 20:25 UTC by andreshndz

This PR is in progress

2022-03-28 21:52 UTC, agarrido19 submitted a review, later dismissed
Se ve chido!

2022-03-28 23:59 UTC, alexviquez requested changes
solo un detalle con los types

2022-03-28 23:59 UTC, alexviquez commented on cuenca_validations/types/enums.py
> +    email_verification = 'email_verification'
si ya se llama verification, para que ponen el sufijo verification, solo pongan phone y email

2022-03-29 00:25 UTC, alexviquez approved these changes

2022-03-29 00:25 UTC, merged