Manual curp validation
cuenca-mx/cuenca-validations pull request #237
Opened 2022-05-03 23:16 UTC by agarrido19

- closes #236

2022-05-03 23:29 UTC, rogelioLpz commented on cuenca_validations/types/requests.py
> +            raise ValueError('manual_curp must be the only param if passed')
Esta no

2022-05-03 23:30 UTC, rogelioLpz commented on cuenca_validations/types/requests.py
> +            raise ValueError('some values required')
Indicar que campos faltan

2022-05-03 23:30 UTC, rogelioLpz commented on tests/test_types.py
> +        manual_curp=None,
revert

2022-05-03 23:30 UTC, rogelioLpz commented on tests/test_types.py
> +        assert 'User does not meet age requirementf.' in str(v)
typo

2022-05-03 23:35 UTC, chiqeen03 requested changes

2022-05-03 23:35 UTC, chiqeen03 commented on cuenca_validations/types/requests.py
> +        names = values.get('names')
Puedes tratar algo así para accesar a los campos de la clase CurpValidator e iterarlos para checar si vienen en el dict de values, para tener un mejor manejo de errores

```python
missing = []
skippable = ['second_surname', 'state_of_birth', 'manual_curp']
for k in cls.__fields__:
    if k in skippable:
        continue
    v = values.get(k)
    if not v:
        missing.append(k)
if missing:
    raise ValueError(f'missing {str(missing)}'}
```

2022-05-03 23:35 UTC, chiqeen03 commented on cuenca_validations/types/requests.py
> +        if manual_curp and any(required_without_manual):
acá se debe de poder pasar el `manual_curp` y demás campos porque hay un campo `renapo_full_match` en Identify para vlaidar que los datos pasados sean iguales a lo que regresa RENAPO

2022-05-03 23:35 UTC, chiqeen03 commented on tests/test_types.py
> +        CurpValidationRequest(**request)
esto no deberá de lanzar error

2022-05-03 23:35 UTC, chiqeen03 commented on tests/test_types.py
> +        assert 'User does not meet age requirementf.' in str(v)
typo

2022-05-03 23:36 UTC, chiqeen03 commented on cuenca_validations/types/requests.py
> +        names = values.get('names')
@rogelioLpz a lo mejor a roger se le ocurre una mejor manera

2022-05-03 23:39 UTC, agarrido19 commented on cuenca_validations/types/requests.py
> +            raise ValueError('manual_curp must be the only param if passed')
Done

2022-05-03 23:39 UTC, agarrido19 commented on tests/test_types.py
> +        manual_curp=None,
Done

2022-05-03 23:40 UTC, agarrido19 commented on tests/test_types.py
> +        assert 'User does not meet age requirementf.' in str(v)
Done

2022-05-03 23:40 UTC, chiqeen03 commented on cuenca_validations/types/requests.py
> +        names = values.get('names')
<img width="318" alt="Screenshot 2022-05-03 at 18 40 01" src="https://user-images.githubusercontent.com/23019233/166591925-b02c34b8-4b7c-46e4-b48d-fe12fa26d89d.png">
https://pydantic-docs.helpmanual.io/usage/models/

2022-05-03 23:40 UTC, agarrido19 commented on cuenca_validations/types/requests.py
> +        if manual_curp and any(required_without_manual):
Bambi

2022-05-03 23:40 UTC, agarrido19 commented on tests/test_types.py
> +        CurpValidationRequest(**request)
okaz

2022-05-03 23:40 UTC, agarrido19 commented on tests/test_types.py
> +        assert 'User does not meet age requirementf.' in str(v)
Ya

2022-05-03 23:41 UTC, rogelioLpz commented on cuenca_validations/types/requests.py
> +        names = values.get('names')
```python
required=['names',' first_surname','date_of_birth','country_of_birth','gender']
missing = [r for r in required if r not in values.keys()]
if not manual_curp and not all(required_without_manual):
    raise ValueError(f'Missing fields  {missing}')
```

2022-05-03 23:48 UTC, chiqeen03 commented on cuenca_validations/types/requests.py
> +        names = values.get('names')
> ```python
> required=['names',' first_surname','date_of_birth','country_of_birth','gender']
> missing = [r for r in required if r not in values.keys()]
> if not manual_curp and missing:
>     raise ValueError(f'Missing fields  {missing}')
> ```

+1

2022-05-04 00:11 UTC, chiqeen03 commented
solo cambiar el identify también para que sean campos opcionales

2022-05-04 18:30 UTC, rogelioLpz commented
No tiene 100% de coverage 👎 
Así no se puede ir

2022-05-04 18:45 UTC, agarrido19 commented
@rogelioLpz revisando
<img src="https://media2.giphy.com/media/VbnUQpnihPSIgIXuZv/giphy-downsized-medium.gif"/>

2022-05-04 18:49 UTC, rogelioLpz commented on tests/test_types.py
> +        assert 'required state' in str(v)
Este assert va afuera del with

2022-05-04 18:50 UTC, rogelioLpz commented on tests/test_types.py
> +        assert 'required country' in str(v)
Este igual

2022-05-04 18:53 UTC, alexviquez commented
![image](https://user-images.githubusercontent.com/13012209/166805846-f254a1e3-34b4-4512-a70d-eee7d2f24045.png)

2022-05-04 18:54 UTC, rogelioLpz approved these changes

2022-05-04 18:54 UTC, merged