add identity uri
cuenca-mx/cuenca-validations pull request #247
Opened 2022-06-03 23:08 UTC by agarrido19

PR on progress

2022-06-06 23:58 UTC, andreshndz submitted a review, later dismissed
Lo veo bien

2022-06-07 15:19 UTC, alexviquez requested changes
Debería ser uri

2022-06-07 15:19 UTC, alexviquez commented on cuenca_validations/types/queries.py
> +    identity: Optional[str] = None
identity_uri

2022-06-10 01:39 UTC, agarrido19 commented on cuenca_validations/types/queries.py
> +    identity: Optional[str] = None
ya

2022-06-10 01:53 UTC, andreshndz requested changes
Solo ese camabio

2022-06-10 01:53 UTC, andreshndz commented on cuenca_validations/version.py
> +__version__ = '0.10.9.dev2'
Solo cambiar la version para mergear

2022-06-10 15:08 UTC, agarrido19 commented on cuenca_validations/version.py
> +__version__ = '0.10.9.dev2'
Listo

2022-06-10 15:50 UTC, andreshndz approved these changes

2022-06-10 16:49 UTC, merged