Update/pydantic v2
cuenca-mx/cuenca-validations pull request #360
Opened 2024-12-20 17:09 UTC by gmorales96

### Description:
This PR migrates the project to Pydantic v2 and drops support for Python 3.7

### Key Changes:

1. Updates clabe to version 2.0.0 which includes Pydantic v2 support
2. Dropped Support for Python 3.7
3. Refactored unit tests to work with Pydantic v2 changes

### Breaking Changes:

- Projects using Python 3.7 will no longer be supported.
- Code relying on Pydantic v1 API require updates to work with the new version.

2025-01-06 21:09 UTC, pachCode commented on cuenca_validations/types/general.py
> +StrictPositiveFloat = Annotated[float, Field(strict=True, gt=0)]
creo que valdría la pena ir quitando estos que ya lo maneja pydantic y no tenerlos en la librería, tampoco se usan en muchos proyectos pero no le veo el caso tenerlos definidos aquí si ya lo maneja pydantic
https://github.com/search?q=org%3Acuenca-mx+StrictPositiveFloat&type=code

que opinan @felipao-mx @rogelioLpz

2025-01-06 21:11 UTC, pachCode commented on cuenca_validations/version.py
> +__version__ = '2.0.0.dev9'
poner la versión correcta

2025-01-06 21:13 UTC, pachCode commented on tests/test_errors.py
> +def test_error_codes_and_status():
puedes parametrizar este test https://docs.pytest.org/en/stable/example/parametrize.html

2025-01-06 21:15 UTC, pachCode commented on tests/test_types.py
> +class TestFloatModel(BaseModel):
todos estos test los puedes parametrizar para que quede con menos líneas de código

2025-01-06 21:17 UTC, pachCode requested changes
Algunos cambios

2025-01-06 22:36 UTC, gmorales96 commented on cuenca_validations/version.py
> +__version__ = '2.0.0.dev9'
Realizo el cambio

2025-01-07 04:03 UTC, felipao-mx requested changes

2025-01-07 04:03 UTC, felipao-mx commented on setup.py
> +        'python-dateutil>=2.8.0',
me parece que hay una versión más nueva de esta biblioteca

2025-01-07 04:03 UTC, felipao-mx commented on cuenca_validations/types/requests.py
> +    card_status: Optional[CardStatus] = None  # type: ignore
porque hay tantos `# type: ignore`? si ya no son necesario mejor removerlos y revisar si hay otros lugares donde haya y no deban estar

2025-01-07 04:05 UTC, felipao-mx commented on cuenca_validations/types/requests.py
> +from pydantic.networks import IPvAnyAddress
este es un buen comentario @gmorales96

2025-01-07 04:35 UTC, felipao-mx commented on cuenca_validations/types/queries.py
> +from typing_extensions import Annotated
usar `typing.Annotated` que ya está disponible desde python 3.9

2025-01-07 04:40 UTC, felipao-mx commented on cuenca_validations/types/identities.py
> +
sugiero que para tipos de datos sencillos se use `Annotated`. Parece estar más apegado al PEP de python. https://docs.pydantic.dev/latest/concepts/types/#composing-types-via-annotated.

Además no sería necesario definir el `__get_pydantic_core_schema` ya que esto lo hace pydantic automáticamente

```python
PhoneNumber = Annotated[
    str,
    StringConstraints(
        min_length=10,
        max_length=15,
        pattern=r'^\+?[0-9]{10,14}$'
    )
]
```

Solo aquí investigar si internamente este regex `pattern=r'^\+?[0-9]{10,14}$'` se compila para obtener mayor performance

2025-01-07 04:45 UTC, felipao-mx commented on tests/test_types.py
> +class TestFloatModel(BaseModel):
usar clases con prefix `Test...` en los archivos de tests no te genera warnings?

2025-01-10 17:54 UTC, felipao-mx requested changes

2025-01-15 17:36 UTC, felipao-mx commented on .github/workflows/release.yml
> +        uses: actions/setup-python@v4
veo que en otros actions si está actualizado pero en este no

2025-01-15 18:22 UTC, felipao-mx requested changes
ya casi!

2025-01-15 18:22 UTC, felipao-mx commented on cuenca_validations/types/requests.py
> +    number: Annotated[
en este porqué no se usó `PaymentCardNumber`?

2025-01-15 18:22 UTC, felipao-mx commented on cuenca_validations/types/requests.py
> +    exp_year: Optional[Annotated[int, Field(strict=True, ge=18, le=99)]] = None
veo que están duplicadas los `Annotated` para exp_month, exp_year y cvv en otros validator. 

Debes crear un alias para cada uno de ellos y reutilizarlo donde sea posible

```python
ExpMonth = Annotated[int, Field(strict=True, ge=1, le=12)
class Model(BaseModel):
    exp_month: Optional[ExpMonth]
```

revisar si hay más que se puedan reutilizar

2025-01-15 18:22 UTC, felipao-mx commented on cuenca_validations/validators.py
> +    elif isinstance(item, SecretStr):
este donde se utiliza?

2025-01-15 18:54 UTC, rogelioLpz commented on cuenca_validations/errors.py
> -class CardBinValidationError(PydanticValueError):
Mantener este error heredando de PydanticCustomError

2025-01-15 19:05 UTC, rogelioLpz commented on cuenca_validations/types/card.py
> +        cls, __input_value: str, _: core_schema.ValidationInfo
cambiar a nombre más descriptivos los params
card: str,  info: core_schema.ValidationInfo

2025-01-15 22:06 UTC, rogelioLpz commented on cuenca_validations/types/general.py
> +AnyUrlString = Annotated[AnyUrl, AfterValidator(str)]
Usar los datos nativos de pydantic

2025-01-15 22:27 UTC, rogelioLpz commented on cuenca_validations/types/identities.py
> +PhoneNumber = Annotated[
Usar modelo pydantic

2025-01-15 22:36 UTC, rogelioLpz commented on cuenca_validations/types/general.py
> +        BeforeValidator(validate_only_digits),
Validar si se puede usar una regex y así se elimina validate_only_digits

2025-01-15 22:44 UTC, rogelioLpz commented on cuenca_validations/types/identities.py
> +        ..., description='Specific code of the failure in the step.'
Si te deja quitar los `...` igual creo que es mejor quitarlos. (en todos los lados)

2025-01-15 23:08 UTC, rogelioLpz commented on cuenca_validations/types/queries.py
> +    @field_validator('exp_month', 'exp_year', 'cvv2', 'cvv')
Este no es necesario, remover campos
    exp_month: Optional[int] = None
    exp_year: Optional[int] = None
    cvv: Optional[str] = None
    cvv2: Optional[str] = None
    icvv: Optional[str] = None
    pin_block: Optional[str] = None

2025-01-15 23:11 UTC, rogelioLpz commented on setup.py
> +        'pydantic-extra-types>=2.10.0',
Agregar `phonenumbers` aqui y en el requiriments

2025-01-15 23:21 UTC, gmorales96 commented on cuenca_validations/types/identities.py
> +        ..., description='Specific code of the failure in the step.'
oks

2025-01-15 23:23 UTC, gmorales96 commented on .github/workflows/release.yml
> +          password: ${{ secrets.PYPI_API_TOKEN }}
vava

2025-01-16 18:17 UTC, felipao-mx commented on cuenca_validations/errors.py
> +    def __new__(cls):
normalmente no sobreescribimos `__new__`  podrías explicar cual es el motivo?

2025-01-16 18:24 UTC, felipao-mx commented on cuenca_validations/types/requests.py
> +    amount: Annotated[int, Field(strict=True, ge=0)]
este no sería el equivalente a usar `StrictPositiveInt`?

2025-01-16 18:26 UTC, felipao-mx commented on tests/test_errors.py
> +    assert issubclass(CuencaError, Exception)
no veo que sea necesario probar esto. remover test

2025-01-16 18:29 UTC, felipao-mx commented on tests/test_types.py
> +    assert model.value == value
como `StrictPositiveInt` está construído con validadores de pydantic no es necesario hacer este test. Si fuera una implementación o le hubieramos agregado lógica extra de nosotros entonces si

2025-01-16 18:36 UTC, felipao-mx commented on tests/test_types.py
> +    assert TestRfc(rfc='TAXM840916123')
esto ya no es necesario. además lo que está dentro del `with pytest.raises` solo ejecuta la primer línea que es la primera que falla

2025-01-16 18:47 UTC, felipao-mx commented on cuenca_validations/types/identities.py
> +CurpField = Annotated[
renombrar a Curp

2025-01-16 19:23 UTC, gmorales96 commented on cuenca_validations/errors.py
> +    def __new__(cls):
En Pydantic v2, puedes usar `PydanticCustomError` para tener un mayor control sobre la estructura de los errores. Por ejemplo:

```
@field_validator('foo')
def value_must_equal_bar(cls, v):
    if v != 'bar':
        raise PydanticCustomError(
            'not_a_bar',
            'value is not "bar", got "{wrong_value}"',
            dict(wrong_value=v),
        )
    return v
```

Sin embargo, en este caso, la idea es mantener una clase personalizada como CardBinValidationError para identificar errores específicos de manera más clara. Lo normal sería:

```
class CardBinValidationError(PydanticCustomError):
    code = 'payment_card_number.bin'
    msg_template = (
        'The card number contains a BIN (first six digits) that does not have '
        'a known association with a Mexican bank. To add the association, '
        'please file an issue: '
        'https://github.com/cuenca-mx/cuenca-validations/issues'
    )

    def __init__(self):
        super().__init__(error_type=self.code, message_template=self.msg_template)
```


Sin embargo de esta manera se genera el siguiente error:

`TypeError: PydanticCustomError.__new__() missing 2 required positional arguments: 'error_type' and 'message_template'`

Esto me llevo a sobre scribir el método __new__ 

Sin embargo, creo que lo más adecuado sería simplemente lanzar un PydanticCustomError directamente y, si en algún proyecto se necesita personalizar su comportamiento, realizar los ajustes necesarios en ese contexto.

Que opinan @felipao-mx @rogelioLpz ?

2025-01-16 19:27 UTC, gmorales96 commented on cuenca_validations/types/requests.py
> +    amount: Annotated[int, Field(strict=True, ge=0)]
En este específicamente no, `StrictPositiveInt` es mayor a 0:

```
StrictPositiveInt = Annotated[
    int, Field(strict=True, gt=0, le=MAX_VALUE_IN_DB)
]
```

sin embargo justo en esta existe un comentario que indica que puede ser igual a 0

```
    # In some card_validations amount is equal to 0
    amount: Annotated[int, Field(strict=True, ge=0)]
```

Me parece que lo que podemos hacer es modificar StrictPositiveInt para que pueda ser igual a 0 y ahora usarlo de manera general, estas de acuerdo?

2025-01-16 19:27 UTC, felipao-mx commented on cuenca_validations/errors.py
> +    def __new__(cls):
Estoy de acuerdo con usar directo un `PydanticCustomError`. No veo la necesidad de crear una clase personalizada como `CardBinValidationError` porque cuando se lanza la exception dentro del validator esta se convierte en un `pydantic.ValidationError`. Normalmente con esta exception es suficiente para validar lo que ocurrió.

2025-01-16 19:29 UTC, gmorales96 commented on tests/test_errors.py
> +    assert issubclass(CuencaError, Exception)
Tienes razón, lo retiro

2025-01-16 19:30 UTC, felipao-mx commented on cuenca_validations/types/requests.py
> +    amount: Annotated[int, Field(strict=True, ge=0)]
es verdad no había visto el comentario, dejemoslo así

2025-01-16 19:34 UTC, felipao-mx commented on cuenca_validations/types/card.py
> +Cvv2 = Annotated[
renombrar a Cvv

2025-01-16 20:16 UTC, felipao-mx submitted a review, later dismissed
🎉

2025-01-17 20:09 UTC, felipao-mx submitted a review, later dismissed

2025-01-17 20:32 UTC, rogelioLpz commented on cuenca_validations/types/card.py
> +ExpYear = Annotated[int, Field(strict=True, ge=18, le=99)]
`ge=1`

2025-01-17 21:19 UTC, rogelioLpz approved these changes
A prod!! 🚀 🚀

2025-01-17 21:29 UTC, pachCode approved these changes

2025-01-17 21:29 UTC, merged