add CommissionType in Enum
cuenca-mx/cuenca-validations pull request #50
Opened 2020-10-01 22:21 UTC by kerycdiaz

closes #49

2020-10-01 23:09 UTC, alexviquez requested changes
Una pregunta más que nada, `spei_transfer` es para cuenca sin limites ?

2020-10-01 23:09 UTC, alexviquez commented on cuenca_validations/types/enums.py
> +    spei_transfer = 'spei_transfer'
Parece que `spei_transfer` como tal no se ha usado

2020-10-01 23:13 UTC, kerycdiaz commented on cuenca_validations/types/enums.py
> +    spei_transfer = 'spei_transfer'
Si, pero tenia que añadirlo porque necesitaba que oaxaca ya tuviera los tests y todo listo para cuando eso se agrege

2020-10-01 23:40 UTC, alexviquez commented on cuenca_validations/types/enums.py
> +    spei_transfer = 'spei_transfer'
Creo que por ahora debemos dejarlo sin esta parte a fin de cuentas cuando se agregue no sabemos si va a tener el mismo nombre, o si va a estar aquí, cuando sea necesario mejor lo agregamos y ya actualizamos librería donde vayamos a usar

2020-10-01 23:45 UTC, kerycdiaz commented on cuenca_validations/types/enums.py
> +    spei_transfer = 'spei_transfer'
bueno, tendria que borrar el codigo entonces, los tres repositorios, porque ya quedaron funcionando para que cuando el related_transaction sea un Transfer

Y el que o quiera implementar se le puede complicar un poco si no sabes donde iba el codigo.

Yo lo hice para que ya no exista mas desarrollo ni en vaidations, cuenca-python y oaxaca.

2020-10-01 23:45 UTC, kerycdiaz commented on cuenca_validations/types/enums.py
> +    spei_transfer = 'spei_transfer'
Sinceramente es mas facil cambiar e nombre de un enum que hacer una integracion completa

2020-10-05 21:57 UTC, alexviquez requested changes
Solo unas observaciones

2020-10-05 21:57 UTC, alexviquez commented on cuenca_validations/types/entry.py
> +        return None
Podrías hacerlo de la siguiente manera:

```python
return next(model for model,types in mapper[cls.type].items() if cls.id[:2] in types, None)
```

en donde `None` es el default para el primer item del iterator en caso de no cumplir con la condicional así no necesitas StopIterator

2020-10-05 21:57 UTC, alexviquez commented on cuenca_validations/types/enums.py
> +class LedgerEntryType(str, Enum):
EntryType

2020-10-05 21:57 UTC, alexviquez commented on cuenca_validations/types/entry.py
> +        return v
el argumento debería ser `id` no v

2020-10-05 21:57 UTC, alexviquez commented on cuenca_validations/types/entry.py
> +        return v
el argumento podría ser `entry_type` para no usar v

2020-10-07 20:59 UTC, alexviquez requested changes
Me salieron unas dudas, creo que estamos confundiendo los dos type que se encuentran en una transacción

2020-10-07 20:59 UTC, alexviquez commented on cuenca_validations/types/enums.py
> +    commission = 'commission'
No podemos mezclar TransactionType con LedgerEntryType, ya que una se refiere a el tipo de transacción 'comission', `ledger`, `cash`, etc... y otra se refiere a si fue un descuento o un ingreso `debit` y `credit` hay que seguir separando, ya que un comission a su vez es un debit ya que es un cobro

2020-10-07 20:59 UTC, alexviquez commented on cuenca_validations/types/transaction.py
> +class RelatedTransaction(str):
cambiar nombre del archivo igual que la clase

2020-10-07 20:59 UTC, alexviquez commented on cuenca_validations/types/transaction.py
> +        if type(_type) is not TransactionType:
aplica para TransactionType

2020-10-13 21:33 UTC, alexviquez requested changes
Hablamos del cambio

2020-10-13 21:33 UTC, alexviquez commented on cuenca_validations/types/related_transaction.py
> +)
cambiar por lo que hablamos del url

2020-10-13 22:52 UTC, alexviquez submitted a review, later dismissed

2020-10-13 23:02 UTC, alexviquez approved these changes

2020-10-13 23:03 UTC, merged