Adding fastfunds ct type
cuenca-mx/cuenca-validations pull request #80
Opened 2020-12-22 00:03 UTC by chiqeen03

Adds fast_funds card transaction type for its use in Oaxaca and Core.
closes #79

2020-12-22 00:12 UTC, rogelioLpz requested changes
Cambiar la versión en `cuenca-validations/cuenca_validations/version.py `

2020-12-29 17:37 UTC, alexviquez submitted a review, later dismissed
Primero hacer deploy de oaxaca con este nuevo type y después de core

2020-12-29 17:59 UTC, rogelioLpz submitted a review, later dismissed

2020-12-29 20:25 UTC, alexviquez approved these changes

2020-12-29 20:25 UTC, merged