New cards
cuenca-mx/cuenca-validations pull request #83
Opened 2020-12-29 02:00 UTC by ricardo8990

Agrega los tipos para diferentes emisores de tarjetas y de fondeo.

closes #82

2021-02-01 21:12 UTC, matin commented
Looks good in general. But, what's the use case for updating an API key?

2021-02-01 21:20 UTC, ricardo8990 commented
> Looks good in general. But, what's the use case for updating an API key?

Updating the `ApiKey` is part of this issue: https://github.com/cuenca-mx/cuenca-python/issues/104
Which is part of other PR's: https://github.com/cuenca-mx/cuenca-validations/pull/85 and  https://github.com/cuenca-mx/cuenca-python/pull/105

It's been added here because I needed to rebase the other branch so that I can run tests on `core` for the cards integrations. I'm converting this PR as a Draft since the other one has to be merged first.

2021-02-01 21:56 UTC, matin commented
Makes sense

2021-02-01 21:56 UTC, matin approved these changes

2021-03-24 20:20 UTC, rogelioLpz reviewed
Solo unos comentarios pequeños

2021-03-24 20:20 UTC, rogelioLpz commented on cuenca_validations/types/requests.py
> +    number: StrictStr
hay un tipo `PaymentCardNumber` en `pydantic.types`, podrían revisarlo.
Puede que sea mejor

2021-03-24 20:20 UTC, rogelioLpz commented on cuenca_validations/types/requests.py
> +        strip_whitespace=True, strict=True, min_length=3, max_length=3
agregar restricción para que sean solo dígitos

2021-03-24 21:11 UTC, ricardo8990 commented on cuenca_validations/types/requests.py
> +    number: StrictStr
Si lo usaba, pero para las pruebas unitarias y el ambiente de stage usamos demasiados números que no cumplen con Luhn y fallaban muchos tests.

2021-03-24 21:17 UTC, ricardo8990 commented on cuenca_validations/types/requests.py
> +    number: StrictStr
Lo cambié para que al menos valide que sean 16 dígitos

2021-03-24 21:24 UTC, alexviquez requested changes
Me salió una duda con CardQuery

2021-03-24 21:24 UTC, alexviquez commented on cuenca_validations/types/queries.py
> +    pin_block: Optional[str] = None
CardQuery es para filtrar las tarjetas, en que momento necesitarías filtrar unna por cvv, cvv2, pin_block? en realidad con filtrarla por account_number debería ser suficiente no ?

2021-03-24 21:26 UTC, ricardo8990 commented on cuenca_validations/types/queries.py
> +    pin_block: Optional[str] = None
Para cuando se hace un cargo de tarjeta, se busca por todos los campos para validarla

2021-03-24 21:27 UTC, alexviquez commented on cuenca_validations/types/queries.py
> +    pin_block: Optional[str] = None
eso no sería mejor validarlo después del fetch? es decir el hecho de filtrar por tantos campos haría que un indice compuesto sea más pesado, por tanto conviene más que el indice este en account_number solamente y validar solo esos campos en el servidor, que opinas ?

2021-03-24 21:30 UTC, ricardo8990 commented on cuenca_validations/types/queries.py
> +    pin_block: Optional[str] = None
De acuerdo a las pruebas, utiliza el índice sobre el número de tarjeta y después filtra los demás campos. No vimos ninguna mejora agregando un índice compuesto, no sé si sea porque el número esta encriptado. 
Discutiendo con @pachCode, decidimos que estas validaciones se hagan en `knox`, ya que algunos necesitan del HSM para ser validados

2021-03-24 21:40 UTC, alexviquez approved these changes
va

2021-03-24 21:44 UTC, rogelioLpz commented on cuenca_validations/types/requests.py
> +        ..., strip_whitespace=True, min_length=3, max_length=3, regex=r'\d{3}'
con el regex ya cubre los `min_length` y `max_length` no ?

2021-03-24 21:50 UTC, ricardo8990 commented on cuenca_validations/types/requests.py
> +        ..., strip_whitespace=True, min_length=3, max_length=3, regex=r'\d{3}'
Si, pero esto hace los mensajes de error más claros. De otra forma solo diría que fallo el regex

2021-03-24 21:55 UTC, rogelioLpz approved these changes

2021-03-24 23:28 UTC, merged