Api keys
cuenca-mx/cuenca-validations pull request #96
Opened 2021-02-10 01:22 UTC by felipaoo

modelos para crear y actualizar apikeys

2021-02-10 03:58 UTC, ricardo8990 requested changes

2021-02-10 03:58 UTC, ricardo8990 commented on cuenca_validations/types/requests.py
> +        extra = Extra.forbid
No veo necesaria esta clase. Provoca que uno tenga que ir a ver la definición de dicha clase para saber lo que hace, cuando solo son dos líneas de código y no tiene ninguna lógica realmente.

2021-02-10 16:35 UTC, felipaoo commented on cuenca_validations/types/requests.py
> +        extra = Extra.forbid
lo quité

2021-02-11 02:36 UTC, alexviquez requested changes
Un usuario podría tomar el api key de otro? o porque el update con user_id

2021-02-11 02:36 UTC, alexviquez commented on cuenca_validations/types/requests.py
> +    metadata: Optional[DictStrAny]
que trae metadata como tal? podríamos agregar un comment

2021-02-11 02:36 UTC, alexviquez commented on cuenca_validations/types/requests.py
> +    user_id: Optional[str]
porque el user_id es opcional? un usuario puede tomar el api:key de otro ?

2021-02-11 03:00 UTC, felipaoo commented on cuenca_validations/types/requests.py
> +    metadata: Optional[DictStrAny]
trae los datos que envía la app en el header `X-User-Data`: sistema operativo, tel, dispositivo. 
```
{
"device": "...",
"phone_number": "...",
"so": "..."
}
```

2021-02-11 16:10 UTC, felipaoo commented on cuenca_validations/types/requests.py
> +    user_id: Optional[str]
si un apikey ya está asignada a un usuario ya no puede tomarlo otro. es opcional porque hay un caso donde solo es necesario actualizar el `metadata` del apikey

2021-02-11 20:38 UTC, alexviquez approved these changes
Va dale

2021-02-11 21:30 UTC, ricardo8990 approved these changes

2021-02-11 21:30 UTC, merged